-- Rehberlik icerikleri (Faz 4 Content Hub)
-- Uzak projede apply_migration ile uygulandi; yerel gelistirme icin referans.

CREATE TABLE IF NOT EXISTS public.guidance_contents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  content_type text NOT NULL,
  url text,
  body text,
  target_exam text,
  cover_image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT guidance_contents_type_check
    CHECK (content_type = ANY (ARRAY['blog'::text, 'video'::text, 'pdf'::text])),
  CONSTRAINT guidance_contents_target_exam_check
    CHECK (target_exam IS NULL OR target_exam = ANY (ARRAY['YKS'::text, 'LGS'::text, 'KPSS'::text, 'ARA_SINIF'::text]))
);

CREATE INDEX IF NOT EXISTS guidance_contents_active_type_idx
  ON public.guidance_contents (is_active, content_type);

ALTER TABLE public.guidance_contents ENABLE ROW LEVEL SECURITY;
