-- =============================================================================
-- MINDORA: Randevu Yönetim Modülü
-- Öğretmen müsaitliği, randevu yaşam döngüsü (talep → onay/öneri → görüşme →
-- not), yapılandırılmış görüşme notları, karar/görev takibi ve uygulama içi
-- bildirim + hatırlatma sistemi.
-- =============================================================================

-- ─── 1. Öğretmen randevu ayarları ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teacher_appointment_settings (
  teacher_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  slot_minutes int NOT NULL DEFAULT 30 CHECK (slot_minutes BETWEEN 10 AND 180),
  buffer_minutes int NOT NULL DEFAULT 10 CHECK (buffer_minutes BETWEEN 0 AND 60),
  max_daily int NOT NULL DEFAULT 8 CHECK (max_daily BETWEEN 1 AND 30),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ─── 2. Haftalık müsaitlik kuralları (gün başına birden çok aralık) ──────────
-- day_of_week: ISO — 1 = Pazartesi … 7 = Pazar
CREATE TABLE IF NOT EXISTS public.teacher_availability_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  day_of_week int NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
  start_time time NOT NULL,
  end_time time NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (start_time < end_time)
);

CREATE INDEX IF NOT EXISTS idx_availability_rules_teacher
  ON public.teacher_availability_rules (teacher_id, day_of_week);

-- ─── 3. İstisnalar: tatil / izin / tek seferlik kapalı saat ──────────────────
-- start_time & end_time NULL ise tüm gün kapalıdır.
CREATE TABLE IF NOT EXISTS public.teacher_availability_exceptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  date date NOT NULL,
  start_time time,
  end_time time,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (start_time IS NULL AND end_time IS NULL)
    OR (start_time IS NOT NULL AND end_time IS NOT NULL AND start_time < end_time)
  )
);

CREATE INDEX IF NOT EXISTS idx_availability_exceptions_teacher
  ON public.teacher_availability_exceptions (teacher_id, date);

-- ─── 4. appointments tablosunu genişlet ──────────────────────────────────────
ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS meeting_type text NOT NULL DEFAULT 'student',
  ADD COLUMN IF NOT EXISTS meeting_format text NOT NULL DEFAULT 'online',
  ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS proposed_date timestamptz,
  ADD COLUMN IF NOT EXISTS proposed_by uuid,
  ADD COLUMN IF NOT EXISTS rejection_reason text,
  ADD COLUMN IF NOT EXISTS started_at timestamptz,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz;

ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_status_check;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_status_check
  CHECK (status IN ('pending','proposed','confirmed','in_progress','completed','cancelled','rejected'));

ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_meeting_type_check;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_meeting_type_check
  CHECK (meeting_type IN ('student','parent','joint','program_review','exam_analysis','preference','intro','other'));

ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_meeting_format_check;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_meeting_format_check
  CHECK (meeting_format IN ('online','in_person','phone'));

CREATE INDEX IF NOT EXISTS idx_appointments_teacher_date
  ON public.appointments (teacher_id, appointment_date);

-- ─── 5. Görüşme notları (paylaşılabilir alanlar) ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.meeting_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id bigint NOT NULL UNIQUE REFERENCES public.appointments(id) ON DELETE CASCADE,
  teacher_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject_topic text,
  student_opinion text,
  parent_opinion text,
  visibility text NOT NULL DEFAULT 'teacher'
    CHECK (visibility IN ('teacher','teacher_student','teacher_parent','all')),
  follow_up_topics jsonb NOT NULL DEFAULT '[]'::jsonb,
  next_meeting_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_meeting_notes_student
  ON public.meeting_notes (student_id, created_at DESC);

-- ─── 6. Öğretmenin özel değerlendirmesi (asla öğrenci/veliye açılmaz) ────────
-- Ayrı tabloda tutulur; RLS yalnızca öğretmene izin verir. Böylece görünürlük
-- ayarı ne olursa olsun API üzerinden dahi sızamaz.
CREATE TABLE IF NOT EXISTS public.meeting_private_notes (
  appointment_id bigint PRIMARY KEY REFERENCES public.appointments(id) ON DELETE CASCADE,
  teacher_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  evaluation text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ─── 7. Kararlar / görevler / takip maddeleri ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.meeting_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id bigint NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  teacher_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'decision' CHECK (kind IN ('decision','task','follow_up')),
  text_content text NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  study_plan_task_id bigint REFERENCES public.study_plan_tasks(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_meeting_decisions_appointment
  ON public.meeting_decisions (appointment_id);
CREATE INDEX IF NOT EXISTS idx_meeting_decisions_student
  ON public.meeting_decisions (student_id, is_completed);

-- ─── 8. Uygulama içi bildirimler + zamanlanmış hatırlatmalar ─────────────────
-- deliver_at gelecekte olan satırlar hatırlatmadır; zamanı gelince zilde görünür.
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  appointment_id bigint REFERENCES public.appointments(id) ON DELETE CASCADE,
  deliver_at timestamptz NOT NULL DEFAULT now(),
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user
  ON public.notifications (user_id, deliver_at DESC);

-- =============================================================================
-- RLS
-- =============================================================================
ALTER TABLE public.teacher_appointment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_availability_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_availability_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_private_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Yardımcı: oturum açan kullanıcı verilen öğretmenin öğrencisi mi?
CREATE OR REPLACE FUNCTION public.is_student_of_teacher(p_teacher_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.teacher_id = p_teacher_id AND p.role = 'student'
  );
$$;

-- Müsaitlik: öğretmen tam yetki, öğrenci kendi öğretmenininkini okuyabilir
DROP POLICY IF EXISTS tas_teacher_all ON public.teacher_appointment_settings;
CREATE POLICY tas_teacher_all ON public.teacher_appointment_settings
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());
DROP POLICY IF EXISTS tas_student_select ON public.teacher_appointment_settings;
CREATE POLICY tas_student_select ON public.teacher_appointment_settings
  FOR SELECT TO authenticated USING (public.is_student_of_teacher(teacher_id));

DROP POLICY IF EXISTS tar_teacher_all ON public.teacher_availability_rules;
CREATE POLICY tar_teacher_all ON public.teacher_availability_rules
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());
DROP POLICY IF EXISTS tar_student_select ON public.teacher_availability_rules;
CREATE POLICY tar_student_select ON public.teacher_availability_rules
  FOR SELECT TO authenticated USING (public.is_student_of_teacher(teacher_id));

DROP POLICY IF EXISTS tae_teacher_all ON public.teacher_availability_exceptions;
CREATE POLICY tae_teacher_all ON public.teacher_availability_exceptions
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());
DROP POLICY IF EXISTS tae_student_select ON public.teacher_availability_exceptions;
CREATE POLICY tae_student_select ON public.teacher_availability_exceptions
  FOR SELECT TO authenticated USING (public.is_student_of_teacher(teacher_id));

-- Öğrenci kendi öğretmeninin profilini okuyabilsin (randevu sayfası için).
-- profiles üzerindeki SELECT politikasında profiles'a tekrar sorgu atmak
-- recursion yaratacağından SECURITY DEFINER yardımcı fonksiyon kullanılır.
CREATE OR REPLACE FUNCTION public.my_teacher_id()
RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT teacher_id FROM public.profiles WHERE id = auth.uid();
$$;

REVOKE EXECUTE ON FUNCTION public.my_teacher_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.my_teacher_id() TO authenticated;

DROP POLICY IF EXISTS profiles_select_my_teacher ON public.profiles;
CREATE POLICY profiles_select_my_teacher
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (id = public.my_teacher_id());

-- appointments: öğrenci INSERT politikasını kendi öğretmeniyle sınırla
DROP POLICY IF EXISTS appointments_insert_student ON public.appointments;
CREATE POLICY appointments_insert_student ON public.appointments
  FOR INSERT TO authenticated
  WITH CHECK (student_id = auth.uid() AND public.is_student_of_teacher(teacher_id));

-- Görüşme notları: öğretmen tam yetki; öğrenci görünürlüğe göre okur
DROP POLICY IF EXISTS mn_teacher_all ON public.meeting_notes;
CREATE POLICY mn_teacher_all ON public.meeting_notes
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());
DROP POLICY IF EXISTS mn_student_select ON public.meeting_notes;
CREATE POLICY mn_student_select ON public.meeting_notes
  FOR SELECT TO authenticated
  USING (student_id = auth.uid() AND visibility IN ('teacher_student','all'));

-- Özel notlar: yalnızca öğretmen
DROP POLICY IF EXISTS mpn_teacher_all ON public.meeting_private_notes;
CREATE POLICY mpn_teacher_all ON public.meeting_private_notes
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());

-- Kararlar: öğretmen tam yetki, öğrenci kendi kayıtlarını okur
DROP POLICY IF EXISTS md_teacher_all ON public.meeting_decisions;
CREATE POLICY md_teacher_all ON public.meeting_decisions
  FOR ALL TO authenticated
  USING (teacher_id = auth.uid()) WITH CHECK (teacher_id = auth.uid());
DROP POLICY IF EXISTS md_student_select ON public.meeting_decisions;
CREATE POLICY md_student_select ON public.meeting_decisions
  FOR SELECT TO authenticated USING (student_id = auth.uid());

-- Bildirimler: kullanıcı kendi bildirimlerini okur / okundu işaretler
DROP POLICY IF EXISTS notif_select_own ON public.notifications;
CREATE POLICY notif_select_own ON public.notifications
  FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS notif_update_own ON public.notifications;
CREATE POLICY notif_update_own ON public.notifications
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- =============================================================================
-- Bildirim tetikleyicileri (SECURITY DEFINER: RLS'i aşarak karşı tarafa yazar)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.appointment_reminder_offsets()
RETURNS TABLE (offset_interval interval, label text)
LANGUAGE sql IMMUTABLE AS $$
  VALUES
    (interval '24 hours', '24 saat'),
    (interval '1 hour',  '1 saat'),
    (interval '10 minutes', '10 dakika');
$$;

CREATE OR REPLACE FUNCTION public.create_appointment_reminders(p_appointment public.appointments)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
  v_when text;
BEGIN
  -- Eski hatırlatmaları temizle (saat değişmiş olabilir)
  DELETE FROM public.notifications
  WHERE appointment_id = p_appointment.id AND type = 'reminder' AND deliver_at > now();

  v_when := to_char(p_appointment.appointment_date AT TIME ZONE 'Europe/Istanbul', 'DD.MM.YYYY HH24:MI');

  FOR r IN SELECT * FROM public.appointment_reminder_offsets() LOOP
    IF p_appointment.appointment_date - r.offset_interval > now() THEN
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id, deliver_at)
      VALUES
        (p_appointment.student_id, 'reminder',
         'Randevu hatırlatma',
         'Randevunuza ' || r.label || ' kaldı · ' || v_when,
         p_appointment.id,
         p_appointment.appointment_date - r.offset_interval),
        (p_appointment.teacher_id, 'reminder',
         'Randevu hatırlatma',
         'Randevunuza ' || r.label || ' kaldı · ' || v_when,
         p_appointment.id,
         p_appointment.appointment_date - r.offset_interval);
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_appointment_notifications()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_student_name text;
  v_when text;
  v_proposed text;
BEGIN
  SELECT full_name INTO v_student_name FROM public.profiles WHERE id = NEW.student_id;
  v_when := to_char(NEW.appointment_date AT TIME ZONE 'Europe/Istanbul', 'DD.MM.YYYY HH24:MI');

  IF TG_OP = 'INSERT' THEN
    IF v_actor = NEW.student_id THEN
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (NEW.teacher_id, 'appointment_request', 'Yeni randevu talebi',
              coalesce(v_student_name, 'Öğrenci') || ' · ' || v_when, NEW.id);
    ELSIF NEW.status = 'confirmed' THEN
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (NEW.student_id, 'appointment_confirmed', 'Yeni randevu oluşturuldu',
              'Öğretmeniniz sizin için bir randevu oluşturdu · ' || v_when, NEW.id);
      PERFORM public.create_appointment_reminders(NEW);
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'confirmed' THEN
      IF v_actor = NEW.student_id THEN
        INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
        VALUES (NEW.teacher_id, 'proposal_accepted', 'Önerilen saat kabul edildi',
                coalesce(v_student_name, 'Öğrenci') || ' önerdiğiniz saati kabul etti · ' || v_when, NEW.id);
      ELSE
        INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
        VALUES (NEW.student_id, 'appointment_confirmed', 'Randevunuz onaylandı',
                v_when || ' tarihli randevunuz onaylandı.', NEW.id);
      END IF;
      PERFORM public.create_appointment_reminders(NEW);
    ELSIF NEW.status = 'proposed' THEN
      v_proposed := to_char(NEW.proposed_date AT TIME ZONE 'Europe/Istanbul', 'DD.MM.YYYY HH24:MI');
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (NEW.student_id, 'time_proposed', 'Öğretmeniniz farklı bir saat önerdi',
              'Önerilen yeni saat: ' || coalesce(v_proposed, '-'), NEW.id);
    ELSIF NEW.status = 'pending' AND OLD.status = 'proposed' THEN
      -- Öğrenci öneriyi kabul etmeyip farklı bir saat seçti
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (NEW.teacher_id, 'appointment_request', 'Öğrenci farklı bir saat seçti',
              coalesce(v_student_name, 'Öğrenci') || ' · yeni talep: ' || v_when, NEW.id);
    ELSIF NEW.status = 'rejected' THEN
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (NEW.student_id, 'appointment_rejected', 'Randevu talebiniz reddedildi',
              coalesce(NEW.rejection_reason, v_when || ' tarihli talebiniz reddedildi.'), NEW.id);
    ELSIF NEW.status = 'cancelled' THEN
      INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
      VALUES (CASE WHEN v_actor = NEW.student_id THEN NEW.teacher_id ELSE NEW.student_id END,
              'appointment_cancelled', 'Randevu iptal edildi',
              v_when || ' tarihli randevu iptal edildi.', NEW.id);
      DELETE FROM public.notifications
      WHERE appointment_id = NEW.id AND type = 'reminder' AND deliver_at > now();
    ELSIF NEW.status IN ('completed', 'in_progress') THEN
      NULL; -- bildirim gerekmez
    END IF;
  ELSIF NEW.appointment_date IS DISTINCT FROM OLD.appointment_date AND NEW.status = 'confirmed' THEN
    INSERT INTO public.notifications (user_id, type, title, body, appointment_id)
    VALUES (CASE WHEN v_actor = NEW.student_id THEN NEW.teacher_id ELSE NEW.student_id END,
            'appointment_updated', 'Randevu saati güncellendi',
            'Yeni randevu saati: ' || v_when, NEW.id);
    PERFORM public.create_appointment_reminders(NEW);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_appointment_notifications ON public.appointments;
CREATE TRIGGER trg_appointment_notifications
  AFTER INSERT OR UPDATE ON public.appointments
  FOR EACH ROW EXECUTE FUNCTION public.handle_appointment_notifications();

-- =============================================================================
-- RPC: öğretmenin dolu saat aralıkları (öğrenciye kişisel veri sızdırmadan)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.get_teacher_busy_slots(
  p_teacher_id uuid, p_from date, p_to date
)
RETURNS TABLE (starts_at timestamptz, ends_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT a.appointment_date,
         a.appointment_date + make_interval(mins => a.duration_minutes)
  FROM public.appointments a
  WHERE a.teacher_id = p_teacher_id
    AND a.status IN ('pending','proposed','confirmed','in_progress')
    AND (a.appointment_date AT TIME ZONE 'Europe/Istanbul')::date BETWEEN p_from AND p_to
    AND (
      auth.uid() = p_teacher_id
      OR public.is_student_of_teacher(p_teacher_id)
    );
$$;

-- =============================================================================
-- Program görevi tamamlanınca bağlı görüşme kararını da tamamlandı işaretle
-- =============================================================================
CREATE OR REPLACE FUNCTION public.sync_decision_completion()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.is_completed IS DISTINCT FROM OLD.is_completed THEN
    UPDATE public.meeting_decisions
    SET is_completed = NEW.is_completed,
        completed_at = CASE WHEN NEW.is_completed THEN now() ELSE NULL END
    WHERE study_plan_task_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.sync_decision_completion() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS trg_sync_decision_completion ON public.study_plan_tasks;
CREATE TRIGGER trg_sync_decision_completion
  AFTER UPDATE ON public.study_plan_tasks
  FOR EACH ROW EXECUTE FUNCTION public.sync_decision_completion();

-- ─── Güvenlik sertleştirme (advisor bulguları) ──────────────────────────────
ALTER FUNCTION public.appointment_reminder_offsets() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.create_appointment_reminders(public.appointments) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_appointment_notifications() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_teacher_busy_slots(uuid, date, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_teacher_busy_slots(uuid, date, date) TO authenticated;
